// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhiYpoTd1pPgnGzf1PO8BWWg8HBihvqik',
    appId: '1:713753760311:web:6c594f5b47985c8b5925b2',
    messagingSenderId: '713753760311',
    projectId: 'network-service-test',
    authDomain: 'network-service-test.firebaseapp.com',
    databaseURL: 'https://network-service-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'network-service-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgBkiJgmtoq1u_HyESiZr5lDjPsByLBN8',
    appId: '1:713753760311:android:1497722ffee913485925b2',
    messagingSenderId: '713753760311',
    projectId: 'network-service-test',
    databaseURL: 'https://network-service-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'network-service-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn0AnI7w1hb2GNRLazMqCZJaS3g4eUC10',
    appId: '1:713753760311:ios:638a77e5e92da8735925b2',
    messagingSenderId: '713753760311',
    projectId: 'network-service-test',
    databaseURL: 'https://network-service-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'network-service-test.appspot.com',
    iosClientId: '713753760311-5jth8aqh7cvnvia2mfjb92elktib09gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvvmCompleteTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn0AnI7w1hb2GNRLazMqCZJaS3g4eUC10',
    appId: '1:713753760311:ios:638a77e5e92da8735925b2',
    messagingSenderId: '713753760311',
    projectId: 'network-service-test',
    databaseURL: 'https://network-service-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'network-service-test.appspot.com',
    iosClientId: '713753760311-5jth8aqh7cvnvia2mfjb92elktib09gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvvmCompleteTodoApp',
  );
}
